
all: Talkie
	./talkie_to_ada.py Talkie/src/Vocab_US_Acorn.cpp > ../../src/lpc_synth-vocab_us_acorn.ads
	./talkie_to_ada.py Talkie/src/Vocab_AstroBlaster.cpp > ../../src/lpc_synth-vocab_astroblaster.ads
	./talkie_to_ada.py Talkie/src/Vocab_Soundbites.cpp > ../../src/lpc_synth-vocab_soundbites.ads
	./talkie_to_ada.py Talkie/src/Vocab_Special.cpp > ../../src/lpc_synth-vocab_special.ads
	./talkie_to_ada.py Talkie/src/Vocab_US_Acorn.cpp > ../../src/lpc_synth-vocab_us_acorn.ads
	./talkie_to_ada.py Talkie/src/Vocab_US_Clock.cpp > ../../src/lpc_synth-vocab_us_clock.ads
	./talkie_to_ada.py Talkie/src/Vocab_US_Large.cpp > ../../src/lpc_synth-vocab_us_large.ads
	./talkie_to_ada.py Talkie/src/Vocab_US_TI99.cpp > ../../src/lpc_synth-vocab_us_ti99.ads

Talkie:
	git clone https://github.com/ArminJo/Talkie.git
